### ISSUE TITLE
PV server crashes always with python 3.5.3, sometimes with 3.6.1, never with 2.7.13

### ISSUE THREAD

**Issue by piuupiuupiuu** [paulscherrerinstitute/pcaspy#41]
Hi,
I tried one of the example server (example 1: https://github.com/paulscherrerinstitute/pcaspy/blob/master/example/get_random.py ) and I am stuck in some server crash issue. I installed pcaspy, pyepics via pip for every python version. Servers started in 3.5.3 always crash after following client script finishes: 

```python
from epics import *
import time

pvname = 'MTEST:RAND'

def callback(**kwargs):
        print('Monitor: value is', kwargs['value'][:])

print("1")
camonitor(pvname, callback=callback)

print("2")
time.sleep(3)

print("3")
camonitor_clear(pvname)

print("4")
```

Following error message is given by windows after python.exe crash:
```
  problem event name:	APPCRASH
  application name:	python.exe
  application version:	3.5.3150.1013
  application time stamp:	587cef4a
  error module name:	ntdll.dll
  error module version:	6.1.7601.23714
  error module time stamp:	58bf89e8
  exception code:	c0000005
  exception offset:	000000000004f2a2
  OS version:	6.1.7601.2.1.0.256.4
  Area-ID:	1031
  additional information 1:	2f13
  additional information 2:	2f13ce50ec747d177f6ecd410d6cb989
  additional information 3:	6a04
  additional information 4:	6a04b3682e9230a2aef7d8b0e8c48135
```

There is no crash if the server is called with python 2.7.13. **EDIT: Running in python 3.61 it seems to be sometimes working a while and than just starts crashing again.** 
Any idea on how to proceed with this or where the issue originates?

Thanks!

**Comment by xiaoqiangwang** [comment]
I have reproduced the crash. It happens when the casChannel object gets destroyed, i.e. when the client disconnects itself.

**Comment by piuupiuupiuu** [comment]
Thanks for the fast response! 
Is it possible for me to prevent this?

**Comment by xiaoqiangwang** [comment]
I am still looking for the cause, while it points to a very common function of epics base. E.g. the following simple program crashes, which is unbelievable because it passes the epicsStringTest inside epics base.
```
    char *pUser = epicsStrDup("wang");
    free(pUser);
```

I will provide either a fix or workaround soon, depending on the cause.

**Comment by xiaoqiangwang** [comment]
The direct cause is the usage of epicsStrDup, while the real problem is the mixing of visual studio version. The epics libraries are compiled using VS2008, and Python 3.5 extensions are compiled using VS2015. Calling epicsStrDup will implicitly call malloc with VS2008 runtime, and this memory is then freed with VS2015 runtime. This causes the crash. [This article](http://siomsystems.com/mixing-visual-studio-versions/) article explains this in detail.

This fix bf6d8ac is to use strdup to replace epicsStrDup. Another possible solution, as the article proposed, is to have a free function in epics base. But I am not sure the core team will like it ;)

The binary packages on PyPI and Anaconda are affected. I will make a new release soon,

**Comment by piuupiuupiuu** [comment]
Thanks a lot!! The fix works great! :)

**Comment by xiaoqiangwang** [comment]
0.6.4 has been released with binary packages updated on PyPI and Anaconda.
